### ISSUE TITLE
Can't get to work on M1 Mac

### ISSUE THREAD

**Issue by cameronjlarsen** [FREEZX/com.unity.nvim#1]
First off, thanks for this plugin. It works wonderfully on my Linux desktop but I can't seem to get it to work on my mac book.

I use Homebrew to manage packages and I have set the path for the commands to homebrew bin folder. So "/opt/homebrew/bin/nvim", "/opt/homebrew/bin/nvr", and "/opt/homebrew/bin/alacritty". When I click a file to open I can see a quick flash of what looks like a window opening but nothing happens. Wondering if you can provide any guidance on how I might get this to work?

**Comment by cameronjlarsen** [comment]
After some further tinkering I was finally able to get this to work. I had to set the full path to nvim in the Client arguments section

**Comment by FREEZX** [comment]
Hey, just seeing this. Make sure nvim is in your terminal's PATH environment variable so you wouldn't need the full path.

Also, thanks for confirming this works on Linux and Mac :D
